### ISSUE TITLE
Can I use this as a stream?

### ISSUE THREAD

**Issue by donkee** [serdnam/pino-cloudwatch-transport#7]
We recently had a corporate proxy set up, so I had to make some modification to our app to support that, and I can no longer get this cloudwatch transport to work.

`Error: unable to determine transport target for "@serdnam/pino-cloudwatch-transport"`

I am also using pino-pretty for local logging, and I had to convert that to a stream for it to work correctly. Any ideas?

**Comment by serdnam** [comment]
Hi @donkee! I am not sure I understand what you mean with "converting to a stream", could you elaborate?

**Comment by donkee** [comment]
I'm not super familiar with how pino works, but pino-pretty offers the ability to use it as a stream (whatever that means). https://github.com/pinojs/pino-pretty#usage-as-a-stream

**Comment by donkee** [comment]
Here's the SO post that lead me to that solution: https://stackoverflow.com/questions/71938587/unable-to-determine-transport-target-for-pino-pretty

**Comment by serdnam** [comment]
Right, this package exports an async function that returns the result of calling the `pino-abstract-transform` (https://github.com/pinojs/pino-abstract-transport) function, which is a Stream. You should be able to call [this function](https://github.com/serdnam/pino-cloudwatch-transport/blob/master/index.ts#L39) passing it the [expected argument](https://github.com/serdnam/pino-cloudwatch-transport/blob/master/index.ts#L12C1-L19C2) and it should return a stream that Pino can work with. I have not tried this, but it seems to me like it should work, give it a try and let me know!

**Comment by donkee** [comment]
That appears to work, however I lose mixin support ☹️ 
Here's what it looks like:
```typescript
import serdnam from '@serdnam/pino-cloudwatch-transport';
import { randomUUID } from 'crypto';
import pino from 'pino';
import pretty from 'pino-pretty';

export const logger: any =
  environment === 'Local' || process.env.LOCAL_LOGGER === '1'
    ? pino(
        pretty({
          colorize: true
        })
      )
    : pino(
        await serdnam({
          logGroupName: `${logGroupName}`,
          logStreamName: randomUUID().toString(),
          awsRegion: 'us-east-2'
        })
      );
```

Here's what my mixin config was, in case you have a different way to do it:
```typescript
mixin(_: unknown, level: number) {
  return { levelLabel: logger.levels.labels[level] };
}
```

**Comment by serdnam** [comment]
In your example of how it looks like you don't define the mixin function, is that not it? If you do have the mixin correctly configured and it still doesn't work, then that's weird, but it looks more like a Pino or a `pino-abstract-transport` thing that something related directly to this package; in that case, maybe check the documentation for those to see if you can find a solution.

**Comment by donkee** [comment]
Oh, just a stupid mistake. The mixin goes _before_ the stream in the `pino` function. Everything looks good now! Thanks for your help.

```typescript
export const logger: any =
  environment === 'Local' || process.env.LOCAL_LOGGER === '1'
    ? pino(
        pretty({
          colorize: true
        })
      )
    : pino(
        {
          mixin(_: unknown, level: number) {
            return { levelLabel: logger.levels.labels[level] };
          }
        },
        await serdnam({
          logGroupName: `${logGroupName}`,
          logStreamName: randomUUID().toString(),
          awsRegion: 'us-east-2'
        })
      );
```
